version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magpie-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - magpie-network

  db:
    image: mysql:5.7
    container_name: magpie-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: magpie
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: magpie
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - magpie-network

networks:
  magpie-network:
    driver: bridge

volumes:
  dbdata: 